name: vue deploy to github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: "Person"
        required: true
        default: "kyj"
      home:
        description: "location"
        required: false
        default: "Computer-Science"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.MY_GITHUB_TOKEN}}

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
         node-version: 18.x

      - name: Install dependencies
        run: yarn yarn:ci

      - name: Deploy(Push in github page repository)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
