name: vue deploy to github pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GITHUB_REPOSITORY }}
          token: ${{ secrets.MY_GITHUB_TOKEN}}
          path: GitHubActions

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
         node-version: 18.x

      - name: Build
        uses: borales/actions-yarn@v4
        run: |
          yarn yarn:ci
          yarn build
        

      - name: Deploy(Push in github page repository)
        run: |
          cd GitHubActions

          sudo timedatectl set-timezone Asia/Seoul

          NOW=$(date "+%Y-%m-%d_%H시_%M분_%S초")

          sudo rm -rf .gitignore

          git add dist/.
          git config --global user.email "uni0125@naver.com"
          git config --global user.name "kyj"
          git commit -am "Push date is $NOW"
          git push

